### ISSUE TITLE
Not available for Kindle Paperwhite

### ISSUE THREAD

**Issue by skypjack** [raspofabs/dodbooksourcecode#5]
First of all, thanks for your efforts. I've read the online version of this book a while ago and I think it's very interesting.  
I also wanted to buy the Kindle version when I knew it existed, but I found that it's not available for Kindle Paperwhite.

Do you plan to ever adapt it for this device?  
I don't know what prevents you from doing this. It's often due to images or things rendered in such a way that the Paperwhite cannot really handle, but this book doesn't have something like that afaik.

**Comment by raspofabs** [comment]
Due to the nature of the diagrams in the book, Kindle only supported uploading the book as a pre-paginated PDF. This seemed to be something to do with textbooks in general, and I wasn't able to find a way to fix the problem without a substantial rewrite to split the diagrams to make them fit on any size display.  I believe Knuth has the same issues with The Art of Computer Programming. Diagrams which link to the text have been a bane of HTML, and they are now a bane of Kindle too.
